version: "3"
services:
  generate-certs:
    image: dojot/locust:${DOJOT_VERSION}
    command: >
      bash -c "
        touch ~/.bashrc &&
        echo \"alias generate_certs='python3 -m src.scripts.generate_certs'\" >> /root/.bashrc &&
        tail -F /dev/null"
    volumes:
      # If you are developing using this container, activate these volumes:
      # - ../../../src:/usr/src/app/src
      # - ../../../tests:/usr/src/app/tests
      # - ../../../.pylintrc:/usr/src/app/.pylintrc
      # - ../../../requirements:/usr/src/app/requirements
      # Whether you are developing or running a test, this volume should be active to properly load
      # the certificates:
      - ./cert:/usr/src/app/cert
    environment:
      DOJOT_URL: "http://localhost:8000"
      DOJOT_MQTT_HOST: "localhost"
      DOJOT_MQTT_PORT: "1883"
      DOJOT_ENV: "n"

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

networks:
  default:
    external:
      name: docker_default
